id: A85BDFB2E
title: The General Visualization for Prayers to Guru Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:10:03.571204
  last_modified_at: 2022-03-01 04:10:03.571206
