id: A85BDFB2E
title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:10:03.529610
  last_modified_at: 2022-03-01 04:10:03.529613
