id: A85BDFB2E
title: The Abbreviated Prayer in Seven Chapters
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:10:03.569627
  last_modified_at: 2022-03-01 04:10:03.569631
